var tableauQuestion = [
    {   question : "Si vous conduisez à 80 km h, et vous approchez d'un quartier résidentiel, cela signifie que",
        propositionA : "Vous devez accélérer",
        propositionB : "Vous pouvez accélérer tant qu'il n'y a pas d'autres voitures",
        propositionC : "Vous devrez ralentir",
        propositionD : "Vous pouvez maintenir votre vitesse",
        reponse : "C"},
        
    {   question : "En tournant à gauche sur un feu vert, vous voyez qu'un piéton traverse. Qui est prioritaire ?",
        propositionA : "Les piétons, parce qu'ils peuvent traverser la route n'importe quand",
        propositionB : "Vous, parce que le feu est vert",
        propositionC : "Le piéton, parce que son feu est aussi vert",
        propositionD : "Vous, car les voitures sont toujours prioritaires",
        reponse : "C"},
        
    {   question : "Sauf autre signalisation, la vitesse maximale dans une zone résidentielle est de",
        propositionA : "50 km/h",
        propositionB : "55 km/h",
        propositionC : "60 km/h",
        propositionD : "70 km/h",
        reponse : "A"},
    
    {   question : "Avant chaque changement de voie, vous devez.",
        propositionA : "Vérifier vos rétroviseur ",
        propositionB : "Vérifier vos angles morts",
        propositionC : "Mettre le cligno",
        propositionD : "Faire tout ça",
        reponse : "D"},
        
    {   question : "Quel taux d'alcoolémie est considéré comme illégal ? (conducteurs confirmés)",
        propositionA : "0.1 g/l de sang",
        propositionB : "0.2 g/l de sang",
        propositionC : "0.4 g/l de sang",
        propositionD : "0.7 g/l de sang",
        reponse : "D"},
        
    {   question : "Vous devez vous arrêter jusqu'à ce que tout véhicule d'urgence avec une sirène soit passé, à moins que:",
        propositionA : "Tu es pressé",
        propositionB : "Y'a ta femme qui t'attend ...",
        propositionC : "Vous êtes dans une zone scolaire",
        propositionD : "Vous êtes dans une intersection",
        reponse : "D"},
    
    {   question : "La priorité doit être cédée aux véhicules d'urgence",
        propositionA : "Toujours",
        propositionB : "Quand ils ont l'air pressé",
        propositionC : "Quand ils sont en intervention (sirènes + gyrophares)",
        propositionD : "Quand y'a un bambi sauvage",
        reponse : "C"},
        
    {   question : "Quel style de feu consomme le moins d'énergie?",
        propositionA : "Les feux classiques",
        propositionB : "Les feux xénon",
        propositionC : "Les feux à LED",
        propositionD : "les feux follets",
        reponse : "C"},
        
    {   question : "Vous conduisez sur une autoroute avec une limitation de vitesse à 110 kmh. La plupart du trafic se déplace à 120 kmh, vous pouvez rouler à",
        propositionA : "110 kmh",
        propositionB : "120 kmh",
        propositionC : "125 kmh",
        propositionD : "130 kmh",
        reponse : "A"},
        
    {   question : "Lorsque vous êtes dépassé par un autre véhicule, il est important de",
        propositionA : "Ralentir",
        propositionB : "Accélérer",
        propositionC : "Regarder l'autre conducteur dans les yeux",
        propositionD : "Conserver son allure",
        reponse : "D"},
]
